version: '3'

tasks:
  clean:
    desc: Clean Build Dir
    cmds:
      - rm -rf build
    status:
      - test ! -d build

  mkdir:
    desc: Create Build Dir
    cmds:
      - mkdir -p build
    status:
      - test -d build

  build-dnsacme:
    desc: Build dnsacme
    label: build-{{.TASK}}
    vars:
      DNSACME_COMMIT:
        sh: git rev-parse HEAD
    cmds:
      - task: mkdir
      - |
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} GOMIPS={{.GOMIPS}} \
        go build -trimpath -o build/dnsacme-{{.TASK}} -ldflags \
        "-w -s -X main.commit={{.DNSACME_COMMIT}}" {{.CLI_ARGS}}

  linux-386:
    desc: Build dnsacme(linux/386)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: 386
        }
  linux-amd64:
    desc: Build dnsacme(linux/amd64)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64
        }
  linux-amd64-v3:
    desc: Build dnsacme(linux/amd64-v3)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64,
          GOAMD64: v3
        }
  linux-amd64-v4:
    desc: Build dnsacme(linux/amd64-v4)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64,
          GOAMD64: v4
        }
  linux-armv5:
    desc: Build dnsacme(linux/armv5)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm,
          GOARM: 5
        }
  linux-armv6:
    desc: Build dnsacme(linux/armv6)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm,
          GOARM: 6
        }
  linux-armv7:
    desc: Build dnsacme(linux/armv7)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm,
          GOARM: 7
        }
  linux-arm64:
    desc: Build dnsacme(linux/arm64)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm64
        }
  linux-mips-hardfloat:
    desc: Build dnsacme(linux/mips-hardfloat)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: mips,
          GOMIPS: hardfloat
        }
  linux-mipsle-softfloat:
    desc: Build dnsacme(linux/mipsle-softfloat)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: mipsle,
          GOMIPS: softfloat
        }
  linux-mipsle-hardfloat:
    desc: Build dnsacme(linux/mipsle-hardfloat)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: mipsle,
          GOMIPS: hardfloat
        }
  linux-mips64:
    desc: Build dnsacme(linux/mips64)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: mips64
        }
  linux-mips64le:
    desc: Build dnsacme(linux/mips64le)
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: mips64le
        }

  release:
    cmds:
      - task: clean
      - task: linux-386
      - task: linux-amd64
      - task: linux-amd64-v3
      - task: linux-amd64-v4
      - task: linux-armv5
      - task: linux-armv6
      - task: linux-armv7
      - task: linux-arm64
      - task: linux-mips-hardfloat
      - task: linux-mipsle-softfloat
      - task: linux-mips64
      - task: linux-mips64le

  default:
    cmds:
      - task: build-dnsacme
        vars: {
          TASK: "local"
        }